name: adderlink
description: A dart library for controlling Adderlink devices on an IP network
version: 4.0.0-dev.1
homepage: https://github.com/point-source/adderlink

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chopper: ^7.0.9
  dart_mappable: ^4.1.0
  xml2json: ^6.1.0

dev_dependencies:
  build_runner: ^2.3.2
  chopper_generator: ^7.0.6
  dart_mappable_builder: ^4.1.0
  lints: ^3.0.0
  test: ^1.16.0
