name: adderlink
description: A dart library for controlling Adderlink devices via network
version: 1.0.1
homepage: https://github.com/point-source/adderlink

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  http: ^0.13.4
  xml2json: ^5.3.3

dev_dependencies:
  dart_code_metrics: ^4.15.2
  lints: ^2.0.0
  test: ^1.16.0
